
title: "TACPS"
url: "https://itseg-mq.github.io" # GH Pages root
baseurl: "/website-tacps"                 # repo name
environment: "staging"            # env name
exclude:
  - LICENSE
  - README.md
  - editor-handbook.md
  - maintainer-handbook.md
  - scripts
  - shonan235/index.html.bak
  - tests
